title: Home's Journey Archive
description: Archive of Worlds, Travelers and forgotten Paths

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

sass:
  sass_dir: assets/css

# Навигация
nav_ordering: manual   # будет использовать nav_order из front matter

# Если хочешь отключить поиск
search_enabled: false
