title: "Home's Journey Archive"
description: "Translated and documented by Teantist"

remote_theme: pmarsceill/just-the-docs

color_scheme: dark

search_enabled: true

baseurl: "/Homes-journey-archive"
