title: "Home's Journey Archive"
description: "Translated and documented by Teantist"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: dark

search_enabled: true

baseurl: "/Homes-journey-archive"
